"""added imageName field to Project model

Revision ID: 37ba4b97809b
Revises: c94f9e70136b
Create Date: 2024-11-05 22:43:43.570777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ba4b97809b'
down_revision = 'c94f9e70136b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageName', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_project_imageName'), ['imageName'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_imageName'))
        batch_op.drop_column('imageName')

    # ### end Alembic commands ###
